#Talon CAN IDs
FRONT_LEFT_ID = 2
REAR_LEFT_ID = 4
REAR_RIGHT_ID = 3
FRONT_RIGHT_ID = 1

COMPRESSOR_CAN_ID = 6

BOTTOM_INTAKE_ID = 1
BALL_TICKLER_ID = 2 #Top Intake
RAKE_ID = 3

COLOR_WHEEL_ID = 4

LIFT_WINCH_ID = 5

PCM_ID = 1

#Solenoid IDs
CLIMB_RETRACT_SOLENOID = 0
CLIMB_EXTEND_SOLENOID = 1

BALL_RAKE_RETRACT_SOLENOID = 2
BALL_RAKE_EXTEND_SOLENOID = 3

BALL_HATCH_RETRACT_SOLENOID = 4 
BALL_HATCH_EXTEND_SOLENOID = 5

COLOR_WHEEL_RETRACT_SOLENOID = 6 
COLOR_WHEEL_EXTEND_SOLENOID = 7

#Controller Mappings
XBOX_LEFT_X_AXIS = 0
XBOX_LEFT_Y_AXIS = 1
XBOX_LEFT_TRIGGER_AXIS = 2
XBOX_RIGHT_TRIGGER_AXIS = 3
XBOX_RIGHT_X_AXIS = 4
XBOX_RIGHT_Y_AXIS = 5
XBOX_A = 1
XBOX_B = 2
XBOX_X = 3
XBOX_Y = 4
XBOX_LEFT_BUMPER = 5
XBOX_RIGHT_BUMPER = 6
XBOX_BACK = 7
XBOX_START = 8