from enum import Enum

class RobotMode(Enum):
  AUTO = 1
  TELE = 2
  TEST = 3
  DISABLED = 4

class LiftState(Enum):
  LIFT_START_CONFIGURATION = 1
  LIFT_DEPLOY_EXTEND_PNEUMATIC = 2
  LIFT_DEPLOY_BEGIN = LIFT_DEPLOY_EXTEND_PNEUMATIC
  LIFT_DEPLOY_WAIT1 = 3
  LIFT_DEPLOY_MOVE_TO_PRESET = 4
  LIFT_DEPLOY_RETRACT_PNEUMATIC = 5
  LIFT_DEPLOY_WAIT2 = 6
  LIFT_DEPLOY_MOVE_TO_STOW = 7
  LIFT_DEPLOYED = 8

class LiftPreset(Enum):
  LIFT_PRESET_STOW = 1
  LIFT_PRESET_PORT_LOW = 2
  LIFT_PRESET_PORT_MIDDLE = 3
  LIFT_PRESET_PORT_HIGH = 4
  LIFT_PRESET_HATCH_LOW = 5
  LIFT_PRESET_HATCH_MIDDLE = 6
  LIFT_PRESET_HATCH_HIGH = 7