from enum import Enum

class RobotMode(Enum):
  AUTO = 1
  TELE = 2
  TEST = 3
  DISABLED = 4

class DriveState(Enum):
  FOLLOW_PATH = 1
  OPERATOR_CONTROL = 2

class HarpoonState(Enum):
  HARPOON_STOW_RETRACT_CENTER = 1
  HARPOON_STOW_BEGIN = HARPOON_STOW_RETRACT_CENTER
  HARPOON_STOW_WAIT1 = 2
  HARPOON_STOW_RETRACT_OUTSIDE = 3
  HARPOON_STOW_WAIT2 = 4
  HARPOON_STOWED = 5
  HARPOON_DEPLOY_EXTEND_OUTSIDE = 6
  HARPOON_DEPLOY_BEGIN = HARPOON_DEPLOY_EXTEND_OUTSIDE
  HARPOON_DEPLOY_WAIT1 = 7
  HARPOON_DEPLOY_EXTEND_CENTER = 8
  HARPOON_DEPLOY_WAIT2 = 9
  HARPOON_DEPLOYED = 10

class ClawState(Enum):
  CLAW_STOW_MOVE_TO_STOW = 3
  CLAW_STOW_BEGIN = CLAW_STOW_MOVE_TO_STOW
  CLAW_STOW_WAIT2 = 4
  CLAW_STOWED = 5
  CLAW_DEPLOY = 6
  CLAW_DEPLOY_BEGIN = CLAW_DEPLOY
  CLAW_DEPLOY_WAIT1 = 7
  CLAW_DEPLOYED = 8
  CLAW_SHOOT_BALL = 9
  CLAW_SHOOT_BALL_WAIT1 = 10

class LiftState(Enum):
  LIFT_START_CONFIGURATION = 1
  LIFT_DEPLOY_EXTEND_PNEUMATIC = 2
  LIFT_DEPLOY_BEGIN = LIFT_DEPLOY_EXTEND_PNEUMATIC
  LIFT_DEPLOY_WAIT1 = 3
  LIFT_DEPLOY_MOVE_TO_STOW = 4
  LIFT_DEPLOY_RETRACT_PNEUMATIC = 5
  LIFT_DEPLOY_WAIT2 = 6
  LIFT_DEPLOYED = 7

class LiftPreset(Enum):
  LIFT_PRESET_STOW = 1
  LIFT_PRESET_PORT_LOW = 2
  LIFT_PRESET_PORT_MIDDLE = 3
  LIFT_PRESET_PORT_HIGH = 4
  LIFT_PRESET_HATCH_LOW = 5
  LIFT_PRESET_HATCH_MIDDLE = 6
  LIFT_PRESET_HATCH_HIGH = 7