
import math

#Motion Magic Lift
MIN_POSITION_LIFT = 0 #ticks
MAX_POSITION_LIFT = 100 #ticks
MAX_VELOCITY_LIFT = 1 # ticks/100 ms
CRUISE_VELOCITY_LIFT = 0.8 * MAX_VELOCITY_LIFT # ticks/100 ms
ACCELERATION_LIFT = CRUISE_VELOCITY_LIFT # ticks/100 ms/second
GAIN_F_LIFT = 1023 / MAX_VELOCITY_LIFT
GAIN_P_LIFT = 0
GAIN_I_LIFT = 0
GAIN_D_LIFT = 0
GAIN_IZONE_LIFT = 0

#Motion Magic Wrist
MIN_POSITION_WRIST = 0 #ticks
MAX_POSITION_WRIST = 30 #ticks
MAX_VELOCITY_WRIST = 6 # ticks/100 ms
CRUISE_VELOCITY_WRIST = 0.8 * MAX_VELOCITY_WRIST # ticks/100 ms
ACCELERATION_WRIST = CRUISE_VELOCITY_WRIST # ticks/100 ms/second
GAIN_F_WRIST = 1023 / MAX_VELOCITY_WRIST
GAIN_P_WRIST = 30
GAIN_I_WRIST = 0
GAIN_D_WRIST = 0
GAIN_IZONE_WRIST = 0

#Talon CAN IDs
DRIVE_LEFT_MASTER_CAN_ID = 3
DRIVE_LEFT_SLAVE_CAN_ID = 4
DRIVE_RIGHT_MASTER_CAN_ID = 2
DRIVE_RIGHT_SLAVE_CAN_ID = 1
CLAW_LEFT_WHEELS_CAN_ID = 5
CLAW_RIGHT_WHEELS_CAN_ID = 6
CLAW_WRIST_CAN_ID = 8
LIFT_CAN_ID = 7

CAN_TIMEOUT_MS = 10

#Solenoid Mappings
PCM1_CANID = 9
PCM2_CANID = 10
DRIVE_FRONT_EXTEND_SOLENOID = 3
DRIVE_FRONT_RETRACT_SOLENOID = 2
DRIVE_REAR_EXTEND_SOLENOID = 4
DRIVE_REAR_RETRACT_SOLENOID = 5
CLAW_OPEN_SOLENOID = 2
CLAW_CLOSE_SOLENOID = 3
HARPOON_OUTSIDE_EXTEND_SOLENOID = 5
HARPOON_OUTSIDE_RETRACT_SOLENOID = 4
HARPOON_CENTER_EXTEND_SOLENOID = 0
HARPOON_CENTER_RETRACT_SOLENOID = 1
LIFT_RAISE_SOLENOID = 0
LIFT_LOWER_SOLENOID = 1

#Digital Inputs
AUTO_SWITCH_1 = 0
AUTO_SWITCH_2 = 1
AUTO_SWITCH_3 = 2

#Controller Map
XBOX_LEFT_X_AXIS = 0
XBOX_LEFT_Y_AXIS = 1
XBOX_LEFT_TRIGGER_AXIS = 2
XBOX_RIGHT_TRIGGER_AXIS = 3
XBOX_RIGHT_X_AXIS = 4
XBOX_RIGHT_Y_AXIS = 5
XBOX_A = 1
XBOX_B = 2
XBOX_X = 3
XBOX_Y = 4
XBOX_LEFT_BUMPER = 5
XBOX_RIGHT_BUMPER = 6
XBOX_BACK = 7
XBOX_START = 8