from enum import Enum

class RobotMode(Enum):
  AUTO = 1
  TELE = 2
  TEST = 3
  DISABLED = 4

class ClawState(Enum):
  CLAW_STOW_MOVE_TO_STOW = 3
  CLAW_STOW_BEGIN = CLAW_STOW_MOVE_TO_STOW
  CLAW_STOW_WAIT2 = 4
  CLAW_STOW_HOLD = 5
  CLAW_DEPLOY = 6
  CLAW_DEPLOY_BEGIN = CLAW_DEPLOY
  CLAW_DEPLOY_WAIT1 = 7
  CLAW_DEPLOY_ACTIVE = 8
  CLAW_SHOOT_BALL = 9
  CLAW_SHOOT_BALL_WAIT1 = 10

class LiftState(Enum):
  LIFT_START_CONFIGURATION = 1
  LIFT_DEPLOY_EXTEND_PNEUMATIC = 2
  LIFT_DEPLOY_BEGIN = LIFT_DEPLOY_EXTEND_PNEUMATIC
  LIFT_DEPLOY_WAIT1 = 3
  LIFT_DEPLOY_MOVE_TO_PRESET = 4
  LIFT_DEPLOY_RETRACT_PNEUMATIC = 5
  LIFT_DEPLOY_WAIT2 = 6
  LIFT_DEPLOY_MOVE_TO_STOW = 7
  LIFT_DEPLOYED = 8

class LiftPreset(Enum):
  LIFT_PRESET_STOW = 1
  LIFT_PRESET_PORT_LOW = 2
  LIFT_PRESET_PORT_MIDDLE = 3
  LIFT_PRESET_PORT_HIGH = 4
  LIFT_PRESET_HATCH_LOW = 5
  LIFT_PRESET_HATCH_MIDDLE = 6
  LIFT_PRESET_HATCH_HIGH = 7